version: "3.7"

services:
  bluepoints:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      SPRING_PROFILES_ACTIVE: homologacao
    volumes:
      - ./target:/app

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - maria_data:/var/lib/maria

volumes:
  maria_data: